name: Build test signatures

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
jobs:
  generate_signature_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 #v5.2.0
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: |
          .github/scripts/create_signature_files.sh --release
          .github/scripts/commit.sh
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f #v6.0.0
        with:
          name: signature-file.xml
          path: signature-file.xml
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f #v6.0.0
        with:
          name: container-signature-file.xml
          path: container-signature-file.xml
